version: 1.1.{build}-{branch}

build: false

environment:
  matrix:
    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"

platform:
  - x86

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip install -r dev-requirements.txt"
  - "%PYTHON%/Scripts/pip.exe install pytest"
  - "%PYTHON%/Scripts/pip.exe install pytest-cov"
  - "cd %APPVEYOR_BUILD_FOLDER%"
  - "%PYTHON%/Scripts/pip.exe install -r dev-requirements.txt"
test_script:
  - "%PYTHON%/Scripts/py.test --cov"
